language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6

before_install:
  - composer self-update

install:
  - composer update

script:
  - bin/phpunit --verbose

